config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :courses do
    resources :lessons, only: %i[show new create edit update destroy]
  end

  resources :teachers

  get 'search', to: 'home#search'

  namespace :api do
    namespace :v1 do
      resources :courses, only: %i[index show create], param: :code
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :teacher
  has_many :lessons, dependent: :destroy

  validates :name, presence: true
  validates :code, presence: true, uniqueness: true
  validates :price, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :name, presence: true
  validates :duration, presence: true
  validates :content, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one_attached :profile_picture
  has_many :courses, dependent: :nullify

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < ActionController::API

  def index
    @courses = Course.all
    render json: @courses.as_json(except: [:created_at, :updated_at, :teacher_id],
                                  include: :teacher)
  end

  def show
    @course = Course.find_by!(code: params[:code])
    render json: @course
  rescue ActiveRecord::RecordNotFound
    head 404
  end

  def create
    @course = Course.new(course_params)
    @course.save!

    render json: @course, status: :created
  end

  private
  def course_params
    params.require(:course).permit(:teacher_id, :name, :description, :code, :price,
                                   :enrollment_deadline)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @teachers = Teacher.all
    @courses = Course.all
  end

  def new
    @teachers = Teacher.all
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    msg = t('.success')
    return redirect_to @course, notice: msg if @course.save

    @teachers = Teacher.all
    render :new
  end

  def show
  end

  def edit
    @teachers = Teacher.all
  end

  def update
    msg = t('.success')
    return redirect_to @course, notice: msg if @course.update(course_params)

    @teachers = Teacher.all
    render :edit
  end

  def destroy
    msg = t('.success')
    return redirect_to courses_path, notice: msg if @course and @course.destroy

    redirect_to courses_path, alert: t('course_not_available')
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :code, :price,
                                   :enrollment_deadline, :teacher_id)
  end

  def set_course
    @course = Course.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.where("enrollment_deadline >= ?", Date.today)
  end

  def search
    @courses = Course.where('name like ? OR description like?',
                            "%#{params[:query]}%",
                            "%#{params[:query]}%")
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_course, only: %i[show new create edit update destroy]

  def show
    @lesson = @course.lessons.find_by(id: params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = @course.lessons.new(lesson_params)
    msg = t('.success')
    return redirect_to @course, notice: msg if @lesson.save

    render :new
  end

  def edit
    @lesson = @course.lessons.find_by(id: params[:id])
  end

  def update
    msg = t('.success')
    @lesson = @course.lessons.find_by(id: params[:id])
    return redirect_to @course, notice: msg if @lesson.update(lesson_params)

    render :edit
  end

  def destroy
    msg = t('.success')
    @lesson = @course.lessons.find_by(id: params[:id])
    return redirect_to @course, notice: msg if @lesson and @lesson.destroy

    redirect_to @course, alert: t('lesson_not_available')
  end

  private

  def set_course
    @course = Course.find_by(id: params[:course_id])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :duration, :content)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find_by(id: params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    msg = t('.success')
    return redirect_to @teacher, notice: msg if @teacher.save

    render :new
  end

  def edit
    @teacher = Teacher.find_by(id: params[:id])
  end

  def update
    @teacher = Teacher.find_by(id: params[:id])
    msg = t('.success')
    return redirect_to @teacher, notice: msg if @teacher.update(teacher_params)

    render :edit
  end

  def destroy
    @teacher = Teacher.find_by(id: params[:id])
    msg = t('.success')
    return redirect_to teachers_path, notice: msg if @teacher and @teacher.destroy

    redirect_to teachers_path, alert: t('teacher_not_available')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :email, :bio, :profile_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_with model: course, local: true do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description, size: "30x1" %>
  </p>

  <p>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </p>

  <p>
    <%= f.label :enrollment_deadline %>
    <%= f.date_field :enrollment_deadline %>
  </p>

  <p>
    <%= f.label :teacher_id, t('.teacher') %>
    <%= f.collection_select :teacher_id, teachers, :id, :name %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/courses/edit.html.erb
<p><%= link_to t('back'), courses_path %></p>

<%= render 'shared/errors', object: @course %>

<%= render 'form', course: @course, teachers: @teachers %>

app/views/courses/index.html.erb
<p><%= link_to t('back'), root_path %></p>

<p><%= link_to t('.title'), new_course_path %></p>

<% if @courses.empty? %>
  <%= t('courses_not_available') %>
<% end %>

<div class="container_list">
  <% @courses.each do |course|%>
    <div class="item">
      <h2>
        <%= link_to course.name, course %>
      </h2>

      <p>
        <%= course.description %>
      </p>

      <p>
        <%= number_to_currency course.price %>
      </p>

      <p>
        <%= link_to t('.edit_course'), edit_course_path(course) %> | 
        <%= link_to t('.del_course'), course_path(course), method: :delete %>
      </p>
    </div>
  <% end %>

  <% if @courses.count % 4 != 0 %>
    <% (1..(4 - @courses.count % 4)).each do |empty_block| %>
      <div class="item">
        <h2>
          ---
        </h2>
        <p>
          Por vir...
        </p>
        <p>
          <%= number_to_currency 0, unit: 'R$', separator: ',', delimiter: '.', format: '%u %n' %>
        </p>
        <p>
          ---
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<p><%= link_to t('back'), courses_path %></p>

<%= render 'shared/errors', object: @course %>

<%= render 'form', course: @course, teachers: @teachers %>

app/views/courses/show.html.erb
<p><%= link_to t('back'), courses_path %></p>

<% if @course %>
  <h2>
    <%= @course.name %>
  </h2>

  <% if user_signed_in? %>
    <p>
      <%= link_to t('.purchase_course'), '#' %>
    </p>
  <% else %>
    <p>'Necessário estar logado para comprar curso!'</p>
  <% end %>

  <p>
    <%= @course.description %>
  </p>

  <p>
    <%= @course.code %>
  </p>

  <p>
    <%= number_to_currency @course.price %>
  </p>

  <p>
    <%= I18n.localize(@course.enrollment_deadline) %>
  </p>

  <p>
    <%= "#{t('.teacher')}: #{ @course.teacher.name }" %>
  </p>

  <p>
    <%= link_to t('.add_lesson'), new_course_lesson_path(@course) %>
  </p>

  <% if @course.lessons.empty? %>
    <%= t('lessons_not_available') %>
  <% else %>
    <div>
      <% @course.lessons.each do |lesson| %>
        <p>
          <%= link_to lesson.name, course_lesson_path(@course, lesson) %>
        </p>

        <p>
          <%= t('lessons.duration', count: lesson.duration)  %>
        </p>

        <p>
          <%= link_to t('.edit_lesson'), edit_course_lesson_path(@course, lesson) %> |
          <%= link_to t('.del_lesson'), course_lesson_path(@course, lesson), method: :delete %>
        </p>

      <% end %>
    </div>
  <% end%>

  <p>
    <%= link_to t('.edit_course'), edit_course_path(@course) %> | 
    <%= link_to t('.del_course'), course_path(@course), method: :delete %>
  </p>

<% else %>
  <p>
    <%= t('course_not_available') %>
  </p>
<% end %>

app/views/home/index.html.erb
<h3><%= t('.title') %></h3>

<%= form_with url: search_path, method: :get do %>
  <p>
    <%= label_tag :query, t('.search') %>
    <%= text_field_tag :query %>
    <%= submit_tag t('.go') %>
  </p>
<% end %>

<% @courses.each do |course| %>
  <p>
    <%= link_to course.name, course %>
  </p>
  <p>
    <%= course.description %>
  </p>
  <p>
    <%= number_to_currency course.price %>
  </p>
<% end %>

app/views/home/search.html.erb
<h3><%= t('.result_search') %></h3>

<% return 'Nenhum resultado encontrado!' if @courses.empty? %>

<% @courses.each do |course| %>

  <p><%= course.name %></p>
  <p><%= number_to_currency course.price %></p>
  <p><%= link_to t('.details'), course_path(course) %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with model: [course, lesson], local: true do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :duration %>
    <%= f.number_field :duration, step: 1 %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lessons/edit.html.erb
<%= link_to t('back'), course_path(@course) %>

<%= render 'shared/errors', object: @lesson %>

<%= render 'form', course: @course, lesson: @lesson %>

app/views/lessons/new.html.erb
<%= link_to t('back'), course_path(@course) %>

<%= render 'shared/errors', object: @lesson %>

<%= render 'form', course: @course, lesson: @lesson %>

app/views/lessons/show.html.erb
<%= link_to t('back'), course_path %>

<h2>Curso: <%= @course.name %></h2>

<p>
  Aula: <%= @lesson.name %>
</p>

<p>
  <%= t('lessons.duration', count: @lesson.duration)  %>
</p>

<p>
  <%= @lesson.content  %>
</p>

<h3>Conteudo do curso</h3>
<% @lesson.course.lessons.each do |lesson| %>
  <p>
    <%= link_to lesson.name, course_lesson_path(@course, lesson) %>
  </p>
<% end %>

app/views/shared/_errors.html.erb
<% object.errors.any? do %>
  <% object.errors.full_messages.each do |message|%>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <%= link_to root_path, class: 'title_link' do %>
      <h1>Codeplay</h1>
    <% end %>

    <nav>
      <span class="nav_item">
        <%= link_to 'Cursos', courses_path %>
      </span class="nav_item"> | 

      <span class="nav_item">
        <%= link_to 'Professores', teachers_path %>
      </span class="nav_item">
    </nav>
  </div>

  <% if user_signed_in? %>
    <p>
      <%= current_user.email %>
    </p>

    <p>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
    </p>
  <% else %>
    <p>
      <%= link_to t('register_me'), new_user_registration_path %>
    </p>

    <p>
      <%= link_to t('log_into_account'), new_user_session_path %>
    </p>
  <% end %>
  <hr>
</header>

app/views/shared/_messages.html.erb
<% if notice %>
  <span class="custom_message custom_notice">
    <p><%= notice %></p>
  </span>
<% end %>

<% if alert %>
  <span class="custom_message custom_alert">
    <p><%= alert %></p>
  </span>
<% end %>

app/views/teachers/_form.html.erb
<%= form_with model: teacher, local: true do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio, size: "30x1" %>
  </p>

  <p>
    <%= f.label :profile_picture %>
    <%= f.file_field :profile_picture %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/teachers/edit.html.erb
<p><%= link_to t('back'), teachers_path %></p>

<%= render 'shared/errors', object: @teacher %>

<%= render 'form', teacher: @teacher %>

app/views/teachers/index.html.erb
<%= link_to t('back'), root_path %>

<p><%= link_to t('.title'), new_teacher_path %></p>

<% if @teachers.empty? %>
  <%= t('no_registered_teacher') %>
<% end %>

<% @teachers.each do |teacher| %>

  <h2>
    <%= link_to teacher.name, teacher %>
  </h2>

  <p>
    <%= teacher.email %>
  </p>

  <p>
    <%= link_to t('.edit_teacher'), edit_teacher_path(teacher) %>
  </p>

  <p id='del-<%= teacher.id %>'>
    <%= link_to t('.del_teacher'), teacher_path(teacher), method: :delete %>
  </p>
<% end %>

app/views/teachers/new.html.erb
<p><%= link_to t('back'), teachers_path %></p>

<%= render 'shared/errors', object: @teacher %>

<%= render 'form', teacher: @teacher %>

app/views/teachers/show.html.erb
<%= link_to t('back'), teachers_path %>

<% if @teacher %>
  <h2>
    <%= @teacher.name %>
  </h2>

  <p>
    <%= @teacher.email %>
  </p>

  <p>
    <%= @teacher.bio %>
  </p>

  <% if @teacher.profile_picture.attached? %>
    <%= image_tag(@teacher.profile_picture) %>
  <% end %>

<% else %>
  <p>
    <%= t('teacher_not_available') %>
  </p>
<% end %>